[2024-02-21T13:23:08.359+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-s3-mlflow.model_training manual__2024-02-21T13:22:43.227567+00:00 [queued]>
[2024-02-21T13:23:08.369+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-s3-mlflow.model_training manual__2024-02-21T13:22:43.227567+00:00 [queued]>
[2024-02-21T13:23:08.370+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T13:23:08.385+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): model_training> on 2024-02-21 13:22:43.227567+00:00
[2024-02-21T13:23:08.394+0000] {standard_task_runner.py:60} INFO - Started process 13177 to run task
[2024-02-21T13:23:08.397+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '***-s3-mlflow', 'model_training', 'manual__2024-02-21T13:22:43.227567+00:00', '--job-id', '205', '--raw', '--subdir', 'DAGS_FOLDER/***-aws-mlflow.py', '--cfg-path', '/tmp/tmp7g1zr14f']
[2024-02-21T13:23:08.400+0000] {standard_task_runner.py:88} INFO - Job 205: Subtask model_training
[2024-02-21T13:23:08.417+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-02-21T13:23:08.449+0000] {task_command.py:423} INFO - Running <TaskInstance: airflow-s3-mlflow.model_training manual__2024-02-21T13:22:43.227567+00:00 [running]> on host b14d6cdb7c29
[2024-02-21T13:23:08.536+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***-s3-mlflow' AIRFLOW_CTX_TASK_ID='model_training' AIRFLOW_CTX_EXECUTION_DATE='2024-02-21T13:22:43.227567+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-21T13:22:43.227567+00:00'
[2024-02-21T13:23:08.553+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-02-21T13:23:10.605+0000] {logging_mixin.py:188} INFO - data file imported from s3
[2024-02-21T13:23:10.608+0000] {logging_mixin.py:188} INFO - data imported from s3
[2024-02-21T13:23:10.652+0000] {logging_mixin.py:188} INFO -  RMSE: 0.8528526258778343
[2024-02-21T13:23:10.659+0000] {logging_mixin.py:188} INFO -  MAE:  0.645031393708269
[2024-02-21T13:23:10.660+0000] {logging_mixin.py:188} INFO -  R2:  0.05367522047772455
[2024-02-21T13:23:10.670+0000] {logging_mixin.py:188} INFO - predict result : 0.05367522047772455
[2024-02-21T13:23:12.074+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-21T13:23:12.086+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=***-s3-mlflow, task_id=model_training, execution_date=20240221T132243, start_date=20240221T132308, end_date=20240221T132312
[2024-02-21T13:23:12.153+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-21T13:23:12.175+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
