[2024-02-20T10:29:26.908+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-s3-mlflow.upload_to_s3 manual__2024-02-20T10:29:15.590274+00:00 [queued]>
[2024-02-20T10:29:26.919+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-s3-mlflow.upload_to_s3 manual__2024-02-20T10:29:15.590274+00:00 [queued]>
[2024-02-20T10:29:26.920+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-20T10:29:26.937+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2024-02-20 10:29:15.590274+00:00
[2024-02-20T10:29:26.952+0000] {standard_task_runner.py:60} INFO - Started process 4278 to run task
[2024-02-20T10:29:26.955+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '***-s3-mlflow', 'upload_to_s3', 'manual__2024-02-20T10:29:15.590274+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/***-aws-mlflow.py', '--cfg-path', '/tmp/tmp9db9e986']
[2024-02-20T10:29:26.958+0000] {standard_task_runner.py:88} INFO - Job 54: Subtask upload_to_s3
[2024-02-20T10:29:26.976+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-02-20T10:29:27.025+0000] {task_command.py:423} INFO - Running <TaskInstance: airflow-s3-mlflow.upload_to_s3 manual__2024-02-20T10:29:15.590274+00:00 [running]> on host 0980836b8fdf
[2024-02-20T10:29:27.133+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***-s3-mlflow' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-20T10:29:15.590274+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-20T10:29:15.590274+00:00'
[2024-02-20T10:29:27.249+0000] {base.py:83} INFO - Using connection ID 's3_conn' for task execution.
[2024-02-20T10:29:27.250+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-02-20T10:29:29.355+0000] {logging_mixin.py:188} INFO - datafile uploaded successfully
[2024-02-20T10:29:29.358+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-20T10:29:29.371+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=***-s3-mlflow, task_id=upload_to_s3, execution_date=20240220T102915, start_date=20240220T102926, end_date=20240220T102929
[2024-02-20T10:29:29.421+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-20T10:29:29.450+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
