[2024-02-20T11:13:00.721+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-s3-mlflow.upload_to_s3 manual__2024-02-20T11:12:43.063889+00:00 [queued]>
[2024-02-20T11:13:00.742+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-s3-mlflow.upload_to_s3 manual__2024-02-20T11:12:43.063889+00:00 [queued]>
[2024-02-20T11:13:00.744+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-20T11:13:00.772+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2024-02-20 11:12:43.063889+00:00
[2024-02-20T11:13:00.785+0000] {standard_task_runner.py:60} INFO - Started process 6203 to run task
[2024-02-20T11:13:00.793+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '***-s3-mlflow', 'upload_to_s3', 'manual__2024-02-20T11:12:43.063889+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/***-aws-mlflow.py', '--cfg-path', '/tmp/tmpc_4ukp67']
[2024-02-20T11:13:00.797+0000] {standard_task_runner.py:88} INFO - Job 80: Subtask upload_to_s3
[2024-02-20T11:13:00.823+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-02-20T11:13:00.874+0000] {task_command.py:423} INFO - Running <TaskInstance: airflow-s3-mlflow.upload_to_s3 manual__2024-02-20T11:12:43.063889+00:00 [running]> on host 0980836b8fdf
[2024-02-20T11:13:00.995+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***-s3-mlflow' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-20T11:12:43.063889+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-20T11:12:43.063889+00:00'
[2024-02-20T11:13:01.376+0000] {base.py:83} INFO - Using connection ID 's3_conn' for task execution.
[2024-02-20T11:13:01.378+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-02-20T11:13:04.106+0000] {logging_mixin.py:188} INFO - datafile uploaded successfully
[2024-02-20T11:13:04.109+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-20T11:13:04.121+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=***-s3-mlflow, task_id=upload_to_s3, execution_date=20240220T111243, start_date=20240220T111300, end_date=20240220T111304
[2024-02-20T11:13:04.183+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-20T11:13:04.222+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
